# Generated by Django 5.1.1 on 2024-11-05 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_upload_id(apps, schema_editor):
    # Populate the `upload_id` for existing `DataUpload` records to avoid integrity errors
    DataUpload = apps.get_model('api', 'DataUpload')
    for record in DataUpload.objects.all():
        record.upload_id = uuid.uuid4()
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dataupload_error_message_and_more'),
    ]

    operations = [
        # Step 1: Temporarily add `upload_id` without the unique constraint
        migrations.AddField(
            model_name='dataupload',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),

        # Step 2: Populate existing records with unique `upload_id` values
        migrations.RunPython(populate_upload_id, migrations.RunPython.noop),

        # Step 3: Alter `upload_id` to enforce the unique constraint
        migrations.AlterField(
            model_name='dataupload',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # Create models for stratified data, upload logs, and valid entries
        migrations.CreateModel(
            name='StratifiedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_groups', models.JSONField()),
                ('gender', models.JSONField()),
                ('topography', models.JSONField()),
                ('histology', models.JSONField()),
                ('behavior', models.JSONField()),
                ('grade', models.JSONField()),
                ('basis_of_diagnosis', models.JSONField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratified_data', to='api.dataupload')),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.dataupload')),
            ],
        ),
        migrations.CreateModel(
            name='ValidEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_entries', to='api.dataupload')),
            ],
        ),
    ]
