# Generated by Django 5.1.1 on 2024-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_masterdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdata',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='masterdata',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='masterdata',
            name='grade',
        ),
        migrations.AddField(
            model_name='masterdata',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='date_of_incidence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='grade_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='behavior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
