# Generated by Django 5.1.1 on 2024-11-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_gender_masterdata_sex_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterdata',
            unique_together={('registration_number', 'date_of_incidence')},
        ),
    ]
