# Generated by Django 5.1.1 on 2024-11-07 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stratifieddata_created_at_validentries_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 7, 3, 18, 35, 51607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 7, 3, 19, 5, 658869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validentries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 7, 3, 19, 10, 99131, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
