# Generated by Django 5.1.1 on 2024-11-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_validentries_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratifieddata',
            name='upload',
        ),
        migrations.AddField(
            model_name='stratifieddata',
            name='upload_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
