# Generated by Django 5.1.1 on 2024-11-07 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_stratifieddata_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratifieddata',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
