# Generated by Django 5.1.1 on 2024-11-07 10:02

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_stratifieddata_upload_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('editor', 'Editor')], default='user', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(default=pyotp.random_base32, max_length=16)),
            ],
        ),
    ]
