# Generated by Django 5.1.1 on 2024-11-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_registry_temp_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='username',
        ),
        migrations.AddField(
            model_name='registry',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry', to=settings.AUTH_USER_MODEL),
        ),
    ]
