# Generated by Django 5.1.1 on 2024-11-07 12:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_registry_email_remove_registry_otp_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='user',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
