# Generated by Django 5.1.1 on 2024-11-07 12:48

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_registry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='user',
        ),
        migrations.AddField(
            model_name='registry',
            name='email',
            field=models.EmailField(default='mutasa.christian@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
        migrations.AddField(
            model_name='registry',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
