# Generated by Django 5.1.1 on 2024-11-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_registry_user_registry_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
