# Generated by Django 5.1.1 on 2024-11-08 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_registry_options_alter_registry_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('logout', 'Logout'), ('upload', 'Data Upload'), ('validation', 'Data Validation'), ('autocorrect', 'Auto-correction'), ('deactivation', 'Account Deactivation'), ('role_change', 'Role Change'), ('report_generation', 'Report Generation')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
